name = "bgremover"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"

# Uncomment and configure for custom domain:
# routes = [
#   { pattern = "yourdomain.com/*", custom_domain = true }
# ]